package com.cabbooking.mapper;

import com.cabbooking.dto.request.CabRegistrationRequest;
import com.cabbooking.dto.response.CabResponse;
import com.cabbooking.model.Cab;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.time.Instant;

@Mapper(componentModel = "spring", uses = {UserMapper.class})
public interface CabMapper {

    // --- 1. Entity to Response (Read) ---
    //TODO: use instant for lastLocationUpdate
    CabResponse toCabResponse(Cab cab);

    // --- 2. Request to Entity (Create) ---
    @Mapping(target = "id", ignore = true)                 // Auto-generated by DB
    @Mapping(target = "driver", ignore = true)             // Set by Service (fetched from DB)
    @Mapping(target = "status", ignore = true)             // Set to default (AVAILABLE) by Entity/Service
    @Mapping(target = "createdAt", ignore = true)          // Set by @PrePersist or Service
    @Mapping(target = "updatedAt", ignore = true)          // Set by @PrePersist or Service
    @Mapping(target = "lastLocationUpdate", ignore = true) // Not present during registration
    Cab toCabEntity(CabRegistrationRequest request);

    // --- 3. Time Conversion Helper ---
    default LocalDateTime map(Instant instant) {
        if (instant == null) {
            return null;
        }
        // Converts UTC Instant to LocalDateTime for the Frontend
        return LocalDateTime.ofInstant(instant, ZoneOffset.UTC);
    }
}